### PR TITLE
Add MacBookAir 6,2 support

### PR DESCRIPTION
**Pull request by agimenez**
Detect the machine type via dmi and add the proper sysfs files to handle the
backlight brightness level.

We rely on the fact that the backlight driver in use is mba6x_bl. It should work
without it, but the stock intel backlight kernel driver sets the screen brigthness at
~5% or ~95% after suspend, rendering the screen too dark or too light until you
reboot.

Had to add the sysfs file paths for the mba6x_bl driver _before_ the intel ones
because the "discovery" logic just loops the array, and even when the mba6x_bl driver
is loaded the intel sysfs files were used to set the backlight level.

Please note that USB product IDs other than the EUR one are placeholders since I
don't have access to other devices. That should be fixed.

Signed-off-by: L. Alberto Giménez <agimenez@sysvalve.es>

### CODE REVIEW

**Comment by bytbox** [comment]
This looks great, thanks!

The USB product IDs are easily infered from the examples above what you added. Would you like to amend the commit to just put them in, assuming the pattern remains intact? (I know of no way to find them.)

Thanks for this,

**Comment by agimenez** [comment]
Hi,

I have updated the mba62 branch, I hope I did the right thing, I could not find documentation about how to rework the pull request without adding commits (maybe that's what I should have done, but I wanted to make the whole thing just a single commit) and I am more used to the plain old git request-pull workflow.

Can you check again please?

Also, are you tracking changes from the original pommed source code or you just forked and split history forever? I would like to contribute the changes to the original pommed code as well since I'm just touching files that should be in pommed as well.

Regards,
L. Alberto

**Comment by bytbox** [comment]
Pommed itself has not been modified in years. It's pretty much a dead project, as far as I can tell. I never meant for pommed-light to become what it seems to be now: it was just supposed to be a single patch removing a bunch of unnecessary files. Honestly, I don't even use a macbook anymore! But this isn't hard to maintain, and people seem to find it useful, so...

Anyway, I think I wasn't clear when I wrot "continue the pattern" above. As I recall, in the previous commit, you said that 0x0282, right? Then the others should be 281, 283, and 284. Am I misremembering?

**Comment by bytbox** [comment]
(But other than that, I think this is good to merge, and I'm happy to do so if you confirm that what you wrote is what you meant.)

**Comment by agimenez** [comment]
Hi,

Thanks for the update, maybe I contribute the changes directly to the debian developers.

Regarding the USB IDs, the one I can assure is right is 0x0291 for the Europe version. Following the progression for previous MacBook definitions, EUR is the highest one, decrementing the value by one each time for JIS, ISO and ANSI, and that's the modification I made. 

I hope that clears things up.

Regards,
L. Alberto

**Comment by bytbox** [comment]
Okay, I see. Well, if it's wrong, somebody will file an issue eventually...

**Pull request merged**
